# apps/ziledigital/docker-compose.yml  (same idea for jeanyvesart, admin)
services:
  ziledigital-app:
    build: .
    container_name: ziledigital-app
    restart: unless-stopped
    env_file: [.env]
    expose: ["3000"]
    networks: [public]
networks:
  public:
    external: true
